version: "2"

services:
  mysqldb:
    image: amitchaulagain/my-mysql

    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=travel

  spring-backend:
    image: spring-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://172.18.0.2:3306/travel?serverTimezone=UTC
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

networks:
  springmysql-net: